config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tweets#index'
  resources :tweets
  resources :users, only: [:show]
end

#  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

#  root  'tweets#index'                       #ルートパスの指定  
# get 'tweets' => 'tweets#index'
#  get   'tweets/new'  =>  'tweets#new'       #ツイート投稿画面
#  post  'tweets'      =>  'tweets#create'    #ツイート投稿機能
#  get   'users/:id'   =>  'users#show'    #Mypageへのルーティング
#  delete  'tweets/:id'  => 'tweets#destroy'
#  patch   'tweets/:id'  => 'tweets#update'
 # get   'tweets/:id/edit'  => 'tweets#edit'
 # get 'tweets/:id' => 'tweets#show'       #ツイート詳細画面

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet               #tweetsテーブルとのアソシエーション
  belongs_to :user                #usersテーブルとのアソシエーション
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :comments               #commentsテーブルとのアソシエーション
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets
  has_many :comments               #commentsテーブルとのアソシエーション
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    comment = Comment.create(text: comment_params[:text], tweet_id: comment_params[:tweet_id], user_id: current_user.id)
    redirect_to "/tweets/#{comment.tweet.id}"   #コメントと結びつくツイートの詳細画面に遷移する  
  end

  private
  def comment_params
    binding.pry
    params.permit(:text, :tweet_id)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :move_to_index, except: [:index, :show]

  def index
    @tweets = Tweet.includes(:user).page(params[:page]).per(5).order("created_at DESC")
    
  end

  def new
  end

  def create
    
    #Tweet.create(image: tweet_params[:image], text: tweet_params[:text], user_id: current_user.id)
    # Tweet.create(image: tweet_params[:image], text: tweet_params[:text], user_id: current_user.id)

    # Tweet.create(tweet_params)
    tweet = Tweet.new(tweet_params)
    tweet.save!

    redirect_to root_path
    
  end


  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy if tweet.user_id == current_user.id
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    if tweet.user_id == current_user.id
      tweet.update!(tweet_params)
    end
  end

  def show

    @tweet = Tweet.find(params[:id])
    # @comments = @tweet.comments.includes(:user)
  
    # @comments = @tweet.comments.includes(:user)    
  end

  private
  def tweet_params
    
    params.require(:tweet).permit(:image, :text).merge(user_id: current_user.id)
    # params.require(:tweet).permit(:image, :text, :user_id)
    # params.require(:review).permit(:nickname, :rate, :review).merge(product_id: params[:product_id])
    # params.permit(:image, :text) 
    
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @tweets = user.tweets.page(params[:page]).per(5).order("created_at DESC")
  end
end  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_notifications.html.erb
<div class="notification">
  <% flash.each do |key, value| %>
    <%= content_tag :div, value, class: key %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiniApp51nakai2</title>
    <style type="text/css" href="./style.css"></style>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>

  </head>

  <body>
    <%= render 'layouts/notifications' %>

    <%= yield %>
  </body>
</html>

app/views/layouts/pic_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pictweet</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script type="text/javascript">
      WebFontConfig = {
        google: { families: [ 'Unica+One::latin' ] }
      };
      (function() {
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
          '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
      })();
    </script>
  </head>

  <body>
   <header class="header">
    <div class="header__bar row">
      <h1 class="grid-6"><a href="/">PicTweet</a></h1>
      <% if user_signed_in? %>
        <div class="user_nav grid-6">
          <span><%= current_user.nickname %>
            <ul class="user__info">
              <li>
                <a href="/users/<%= current_user.id %>">マイページ</a>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </span>
          <a class="post" href="/tweets/new">投稿する</a>
        </div>
      <% else %>
        <div class="grid-6">
          <%= link_to "ログイン", new_user_session_path, :class => 'post' %>
          <%= link_to "新規登録", new_user_registration_path, :class => 'post' %>
        </div>
      <% end %>
    </div>
  </header>





    <%= yield %>

    <footer>
      <p>
        Copyright PicTweet 2014.
      </p>
    </footer>
  </body>
</html>

app/views/layouts/s_application.erb
  <header class="header">
    <div class="header__bar row">
      <h1 class="grid-6"><a href="/">PicTweet</a></h1>
      <% if user_signed_in? %>
        <div class="user_nav grid-6">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
          <a class="post" href="/tweets/new">投稿する</a>
        </div>
      <% else %>
        <div class="grid-6">
          <%= link_to "ログイン", new_user_session_path, class: 'post' %>
          <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
        </div>
      <% end %>
    </div>
  </header>

app/views/shared/_massege.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |key, value| %>
      M.toast({html: '<%= value %>'})
    <% end %>
  </script>
<% end %>

app/views/tweets/_3show.html.erb
<!DOCTYPE html>
<html>
<head>
  <%# <title>Sample</title>
  <style type="text/css" href="./style.css"></style> %>
 <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>

  <script
  src="https://code.jquery.com/jquery-3.4.0.js"
  integrity="sha256-DYZMCC8HTC+QDr5QNaIcfR7VSPtcISykd+6eSmBW5qo="
  crossorigin="anonymous"></script>

</head>
<body>

<nav class="grey darken-1">
  <div class="nav-wrapper">
    <a href="#" class="brand-logo"></a>
    <% if user_signed_in? %>
      <span><%= current_user.nickname %>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li>
            <a href="/users/<%= current_user.id %>">マイページ</a></li>
          <li>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
          </li>
          <li>
          <a href="/tweets/new">投稿する</a>
          </li>
        </ul>
      </span>

    <% else %>
        <ul id="nav-mobile" class="right hide-on-med-and-down"> 
          <li>
            <%= link_to "ログイン", new_user_session_path, :class => 'post' %>
          </li>
          <li>
            <%= link_to "新規登録", new_user_registration_path, :class => 'post' %>
          </li>        
        </ul>
    <% end %>         
  </div>
</nav>


<h3>Blog</h3>

   <%# <% if user_signed_in? && current_user.id == @tweet.user_id %> 
<%# <div class="content_post" style="background-image: url(<%= ＠tweet.image %>
<div class="more"> 
  <ul class="more_list">
    <div class="row">
      <div class="col s12 m8">
        <div class="card grey darken-1">
          <%# <%= @tweet.image? %> 
            <div class="card-image">
              <img src="<%= @tweet.image %>">              
                <div class="card-content white-text">
                  <span class="card-title">コメント</span>
                </div>
            </div>
            <div class="card-content">
              <%= simple_format(@tweet.text) %>
                <span class="name">
                  <a href="/users/<%= @tweet.user_id %>">
                    <span>投稿者<%= @tweet.user.nickname %></span>      
                  </a>
                </span>
            </div>
            <div class="card-action">
                <%# <%= link_to '詳細', "/tweets/#{tweet.id}", method: :get %> 
              <% if user_signed_in? && current_user.id == @tweet.user_id %>          
                <%= link_to '編集', "/tweets/#{@tweet.id}/edit", method: :get %>
                <%= link_to '削除', "/tweets/#{@tweet.id}", method: :delete %>
              <% end %>
            </div>
            <%# <div class="card-reveal">
              <span class="card-title grey-text text-darken-4"><i class="material-icons right">close</i>コメント一覧</span>               
                  <%# <div class="comments">   
                  <h4>＜コメント一覧＞</h4> %>
                <% if @comments %>
                  <% @comments.each do |comment| %>
                    <p>
                      <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
                        <%= comment.text %>
                    </p>
                  <% end %>
                <% end %>
            </div> %>
        </div>
      </div>
    </div>  
  </ul> 
</div>

 <%# <div class="container">  %>

  <div class="row">
    <form class="col s12">
      <div class="row">
        <div class="input-field col s12">
          <% if current_user %>
            <%= form_tag("/tweets/#{@tweet.id}/comments", method: :post) do %> 
            <%# <%= form_for [@product, @review] do |f| %> 
            <%# <%= form_for [@tweet, @comment] do |f| %> 
            <%# <%= form_for :tweets, :comments, local: true, url: {action: 'create'} do |f| %>
              <textarea id="textarea1" class="materialize-textarea" cols="30" name="text" placeholder="コメントする" rows="2"></textarea>
              <button class="btn aves-effect waves-light" type="submit" name="action">SENT
              </button>
            <% end %>
          <% end %>
        </div>
      </div>
    </form>
  </div>

<%# <%= paginate(@tweets) %> 

<script type="text/javascript" src="./app.js"></script>
</body>
</html>

app/views/tweets/_index.html.erb
    <div class="content_post" style="background-image: url(<%= tweet.image %>);">
      <div class="more"> 
      <ul class="more_list">

      <div class="row">
        <div class="col s12 m6">
          <div class="card grey darken-1">
            <div class="card-content white-text">
              <span class="card-title">コメント</span>
                <%= simple_format(tweet.text) %>
                <span class="name">
                  <a href="/users/<%= tweet.user_id %>">
                    <span>投稿者<%= tweet.user.nickname %></span>
      
                  </a>
                </span>
            </div>
            <div class="card-action">
              <%= link_to '詳細', "/tweets/#{tweet.id}", method: :get %>
              <% if user_signed_in? && current_user.id == tweet.user_id %>          
                <%= link_to '編集', "/tweets/#{tweet.id}/edit", method: :get %>
                <%= link_to '削除', "/tweets/#{tweet.id}", method: :delete %>
              <% end %>
            </div>
          </div>
        </div>
      </div>  
      </ul>

app/views/tweets/_show.html.1.erb
<!DOCTYPE html>
<html>
<head>
  <%# <title>Sample</title>
  <style type="text/css" href="./style.css"></style> %>
 <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>

  <script
  src="https://code.jquery.com/jquery-3.4.0.js"
  integrity="sha256-DYZMCC8HTC+QDr5QNaIcfR7VSPtcISykd+6eSmBW5qo="
  crossorigin="anonymous"></script>

</head>
<body>

<nav class="grey darken-1">
  <div class="nav-wrapper">
    <a href="#" class="brand-logo"></a>
    <% if user_signed_in? %>
      <span><%= current_user.nickname %>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li>
            <a href="/users/<%= current_user.id %>">マイページ</a></li>
          <li>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
          </li>
          <li>
          <a href="/tweets/new">投稿する</a>
          </li>
        </ul>
      </span>

    <% else %>
        <ul id="nav-mobile" class="right hide-on-med-and-down"> 
          <li>
            <%= link_to "ログイン", new_user_session_path, :class => 'post' %>
          </li>
          <li>
            <%= link_to "新規登録", new_user_registration_path, :class => 'post' %>
          </li>        
        </ul>
    <% end %>         
  </div>
</nav>


<h3>Blog</h3>

   <%# <% if user_signed_in? && current_user.id == @tweet.user_id %> 
<%# <div class="content_post" style="background-image: url(<%= ＠tweet.image %>
<div class="more"> 
  <ul class="more_list">
    <div class="row">
      <div class="col s12 m8">
        <div class="card grey darken-1">
          <%# <%= @tweet.image? %> 
            <div class="card-image">
              <img src="<%= @tweet.image %>">              
                <div class="card-content white-text">
                  <span class="card-title">コメント</span>
                </div>
            </div>
            <div class="card-content">
              <%= simple_format(@tweet.text) %>
                <span class="name">
                  <a href="/users/<%= @tweet.user_id %>">
                    <span>投稿者<%= @tweet.user.nickname %></span>      
                  </a>
                </span>
            </div>
            <div class="card-action">
                <%# <%= link_to '詳細', "/tweets/#{tweet.id}", method: :get %> 
              <% if user_signed_in? && current_user.id == @tweet.user_id %>          
                <%= link_to '編集', "/tweets/#{@tweet.id}/edit", method: :get %>
                <%= link_to '削除', "/tweets/#{@tweet.id}", method: :delete %>
              <% end %>
            </div>
            <%# <div class="card-reveal">
              <span class="card-title grey-text text-darken-4"><i class="material-icons right">close</i>コメント一覧</span>               
                  <%# <div class="comments">   
                  <h4>＜コメント一覧＞</h4> %>
                <% if @comments %>
                  <% @comments.each do |comment| %>
                    <p>
                      <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
                        <%= comment.text %>
                    </p>
                  <% end %>
                <% end %>
            </div> %>
        </div>
      </div>
    </div>  
  </ul> 
</div>

 <%# <div class="container">  %>

  <div class="row">
    <form class="col s12">
      <div class="row">
        <div class="input-field col s12">
          <% if current_user %>
            <%= form_tag("/tweets/#{@tweet.id}/comments", method: :post) do %> 
            <%# <%= form_for [@product, @review] do |f| %> 
            <%# <%= form_for [@tweet, @comment] do |f| %> 
            <%# <%= form_for :tweets, :comments, local: true, url: {action: 'create'} do |f| %>
              <textarea id="textarea1" class="materialize-textarea" cols="30" name="text" placeholder="コメントする" rows="2"></textarea>
              <button class="btn aves-effect waves-light" type="submit" name="action">SENT
              </button>
            <% end %>
          <% end %>
        </div>
      </div>
    </form>
  </div>

<%# <%= paginate(@tweets) %> 

<script type="text/javascript" src="./app.js"></script>
</body>
</html>

app/views/tweets/_show.html.erb
<div class ="contents row">
  <div class="content_post" style="background-image: url(<%= @tweet.image %>);">
    <% if user_signed_in? && current_user.id == @tweet.user_id %>
      <div class="more">
        <span><%= image_tag 'arrow_top.png' %></span>
      <ul class="more_list">
        <li>
          <%= link_to '編集', "/tweets/#{@tweet.id}/edit", method: :get %>
        </li>
        <li>
          <%= link_to '削除', "/tweets/#{@tweet.id}", method: :delete %>
        </li>
      </ul>
    </div>
    <% end %>
    <%= simple_format(@tweet.text) %>
    <span class="name">
      <a href="/users/<%= @tweet.user.id %>">
        <span>投稿者</span><%= @tweet.user.nickname %>
      </a>
    </span>
  </div>
</div>

app/views/tweets/create.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sample</title>
  <style type="text/css" href="./style.css"></style>

  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>

  <script
  src="https://code.jquery.com/jquery-3.4.0.js"
  integrity="sha256-DYZMCC8HTC+QDr5QNaIcfR7VSPtcISykd+6eSmBW5qo="
  crossorigin="anonymous"></script>

</head>

<body>

<nav class="grey darken-1">
  <div class="nav-wrapper">
    <a href="#" class="brand-logo">Blog</a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">     
    </ul>
  </div>
</nav>

<h3>Hello World</h3>

<div class="contents row">
  <div class="container">

      <h5>
        投稿が完了しました。
      </h5>
      <a class="waves-effect waves-light btn-small" href="/tweets">投稿一覧へ戻る</a>

</div>
</div>

app/views/tweets/destroy.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sample</title>
  <style type="text/css" href="./style.css"></style>

</head>

<body>

<nav class="grey darken-1">
  <div class="nav-wrapper">
    <a href="#" class="brand-logo">Blog</a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">     
    </ul>
  </div>
</nav>

<h4></h4>

<div class="contents row">
  <div class="container">

      <h5>
        削除が完了しました。
      </h5>

      <%# <a class="waves-effect waves-light btn-small" href="/tweets">投稿一覧へ戻る</a> %>
      <a class="btn aves-effect waves-light" href="/tweets">投稿一覧へ戻る</a>
      <%# <button class="btn aves-effect waves-light" type="submit" name="action" href="/tweets">投稿一覧へ戻る
      </button> %>
  </div>
  

app/views/tweets/edit.html.erb
<div class="contents row">
  <div class="container">
     <div class="contents row">
    
      <h4>
        Blogコメントの編集
      </h4>
      <%# <%= form_for :@tweet, local: true, url: {action: 'update'} do |f| %>  
       <%= form_with model: @tweet, local: true do |f| %> 
        <%= f.label :image %><br />
        <%= f.text_field :image, placeholder: "Image Url" %>

        <%= f.label :text %>
        <%= f.text_field :text, cols: "30", rows: "10"%>

      
        <button class="btn aves-effect waves-light" type="submit" name="action">更新する
        </button>

      <% end %>
    </div>
  </div>
</div>

app/views/tweets/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sample</title>
  <style type="text/css" href="./style.css"></style>

</head>
<body>

<nav class="grey darken-1">
  <div class="nav-wrapper">
    <a href="#" class="brand-logo"></a>

        <ul id="nav-mobile" class="left hide-on-med-and-down">
          <li>
             <a href="/" ><h4>Blog</h4></a></li>
          <%# <li>
            <a href="">ユーザー：<%= current_user.nickname %></a></li> 
        </ul>

    <% if user_signed_in? %>

        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li>
            <a href="/users/<%= current_user.id %>">マイページ</a></li>
          <li>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
          </li>
          <li>
          <a href="/tweets/new">投稿する</a>
          </li>
        </ul>

    <% else %>
        <ul id="nav-mobile" class="right hide-on-med-and-down"> 
          <li>
            <%= link_to "ログイン", new_user_session_path, :class => 'post' %>
          </li>
          <li>
            <%= link_to "新規登録", new_user_registration_path, :class => 'post' %>
          </li>        
        </ul>
    <% end %>         
  </div>
</nav>

    <h3></h3>
    <% @tweets.each do |tweet| %>

      <div class="content_post" style="background-image: url(<%= tweet.image %>);">
        <div class="more"> 
        <ul class="more_list">

        <div class="row">
          <div class="col s12 m6">
            <div class="card grey darken-1">
              <div class="card-content white-text">
                <span class="card-title">Blogコメント</span>
                  <%= simple_format(tweet.text) %>
                  <span class="name">
                    <a href="/users/<%= tweet.user_id %>">
                      <span>投稿者<%= tweet.user.nickname %></span>
        
                    </a>
                  </span>
              </div>
              <div class="card-action">
                    <%= link_to '詳細', "/tweets/#{tweet.id}", method: :get %>
                    <%# <%= link_to '詳細', tweet_path(tweet) %>
                <% if user_signed_in? && current_user.id == tweet.user_id %>                 
                    <%= link_to '編集', edit_tweet_path(tweet) %>                
                    <%= link_to "削除", "/tweets/#{tweet.id}", method: :delete, data: { confirm: "本当に削除しますか？" } %>                  
                <% end %>
                </ul>
              </div>
            </div>
          </div>
        </div>  
        </ul>
    <% end %>

  <%= paginate(@tweets) %>

  <script type="text/javascript" src="./app.js"></script>


</body>
</html>

app/views/tweets/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sample</title>
  <style type="text/css" href="./style.css"></style>

</head>
<body>

<nav class="grey darken-1">
  <div class="nav-wrapper">
    <a href="/" class="brand-logo">Blog</a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      
    </ul>
  </div>
</nav>

<h3></h3>

<div class="contents row">
  <div class="container">
      <h5>
        Blogコメントの投稿
      </h5>

    <%= form_for :tweet, local: true, url: {action: 'create'} do |f| %>
    <%# <%= form_with model: @tweet, local: true do |f| %>  

      <%= f.label :image %><br />
      <%= f.text_field :image, placeholder: "Image Url" %>

      <%= f.label :text %>
      <%= f.text_field :text, cols: "30", rows: "10"%>
    
      <button class="btn aves-effect waves-light" type="submit" name="action">投稿する
      </button>
      <%# <%= f.submit "SENT" %> 

    <% end %>
    
  </div>
</div>

app/views/tweets/show.html.erb
<!DOCTYPE html>
<html>
<head>
 
</head>
<body>

<nav class="grey darken-1">
  <div class="nav-wrapper">
    <a href="#" class="brand-logo"></a>

        <ul id="nav-mobile" class="left hide-on-med-and-down">
          <li>
             <a href="/" ><h4>Blog</h4></a></li>
            <%# <h4>Blog</h4></li> %>
          <li>
            <a href="" >投稿者：<%= @tweet.user.nickname %></a></li>
        </ul>

    <% if user_signed_in? %>

        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li>
            <a href="/users/<%= current_user.id %>">マイページ</a></li>
          <li>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
          </li>
          <li>
          <a href="/tweets/new">投稿する</a>
          </li>

        </ul>



    <% else %>
        <ul id="nav-mobile" class="right hide-on-med-and-down"> 
          <li>
            <%= link_to "ログイン", new_user_session_path, :class => 'post' %>
          </li>
          <li>
            <%= link_to "新規登録", new_user_registration_path, :class => 'post' %>
          </li>        
        </ul>
    <% end %>         
  </div>
</nav>


<h3></h3>

<div class="more"> 
  <ul class="more_list">
    <div class="row">
      <div class="col s12 m10">
        <div class="card grey darken-1">
          <%# <%= @tweet.image? %> 
            <div class="card-image">
              <img src="<%= @tweet.image %>">              
                <div class="card-content white-text">
                  <span class="card-title">Blogコメント</span>
                </div>
            </div>
            <div class="card-content">
              <%= simple_format(@tweet.text) %>
                <span class="name">
                  <a href="/users/<%= @tweet.user_id %>">
                    <span>投稿者<%= @tweet.user.nickname %></span>      
                  </a>
                </span>
            </div>
            <div class="card-action">
                <%= link_to '詳細', "/tweets/#{@tweet.id}", method: :get %>
              <% if user_signed_in? && current_user.id == @tweet.user_id %>          
                <%= link_to '編集', "/tweets/#{@tweet.id}/edit", method: :get %>
                <%= link_to "削除", "/tweets/#{@tweet.id}", method: :delete, data: { confirm: "本当に削除しますか？" } %> 
              <% end %>
            </div>
        </div>
      </div>
    </div>  
  </ul> 
</div>

 <%# <div class="container">  %>

<%# <%= paginate(@tweets) %> 

<script type="text/javascript" src="./app.js"></script>
</body>
</html>

app/views/users/ss_show.html.erb
  <div class="contents row" >
    <p><%= @nickname %>さんの投稿一覧</p>
    <% @tweets.each do |tweet| %>
      <div class="content_post" style="background-image: url(<%= tweet.image %>);">
        <%= simple_format(tweet.text) %>
      </div>
    <% end %>
    <%= paginate(@tweets) %>
  </div>